# Generated by Django 5.1.4 on 2025-02-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_chef_event_gallery_special_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='offers',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
